// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKarkkDSIlAvJ4RZvNfntu66jZrmWlJEY',
    appId: '1:1063889423103:web:d139283be9cc3889fb9aca',
    messagingSenderId: '1063889423103',
    projectId: 'fruits-hup-f73f5',
    authDomain: 'fruits-hup-f73f5.firebaseapp.com',
    storageBucket: 'fruits-hup-f73f5.firebasestorage.app',
    measurementId: 'G-XM4QXN8C21',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKnj4LCgoIMQiXdci2cou4eps9Vau2m-o',
    appId: '1:1063889423103:android:03c99ff3322c8d48fb9aca',
    messagingSenderId: '1063889423103',
    projectId: 'fruits-hup-f73f5',
    storageBucket: 'fruits-hup-f73f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxRHb0GDP4bugiVfDGTRquezooGNbOeiw',
    appId: '1:1063889423103:ios:0b6bff7b2f853341fb9aca',
    messagingSenderId: '1063889423103',
    projectId: 'fruits-hup-f73f5',
    storageBucket: 'fruits-hup-f73f5.firebasestorage.app',
    iosBundleId: 'com.example.fruitHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxRHb0GDP4bugiVfDGTRquezooGNbOeiw',
    appId: '1:1063889423103:ios:0b6bff7b2f853341fb9aca',
    messagingSenderId: '1063889423103',
    projectId: 'fruits-hup-f73f5',
    storageBucket: 'fruits-hup-f73f5.firebasestorage.app',
    iosBundleId: 'com.example.fruitHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKarkkDSIlAvJ4RZvNfntu66jZrmWlJEY',
    appId: '1:1063889423103:web:b67aae8b8c2fbfc9fb9aca',
    messagingSenderId: '1063889423103',
    projectId: 'fruits-hup-f73f5',
    authDomain: 'fruits-hup-f73f5.firebaseapp.com',
    storageBucket: 'fruits-hup-f73f5.firebasestorage.app',
    measurementId: 'G-Z9T5M8VB1J',
  );
}
